baseURL = '/'
languageCode = 'en-us'
theme = "etch"
[languages]
  [languages.en]
    title = ""
    languageName = "en"
    weight = 1
  [languages.es]
    title = ""
    languageName = "es"
    weight = 2


